const REFRESH_TOKEN_AGE = 1000 * 60 * 60 * 24 * 365;
const ACCESS_TOKEN_AGE = 1000 * 60 * 60;
const ACCESS_TOKEN_EXPIRES_IN = '1h';
const REFRESH_TOKEN_EXPIRES_IN = '1y';
const REFRESH_TOKEN_GENERATION_ALGORITHM = 'HS256';
const ACCESS_TOKEN_GENERATION_ALGORITHM = 'RS256';

export {
  REFRESH_TOKEN_AGE,
  ACCESS_TOKEN_AGE,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_GENERATION_ALGORITHM,
  ACCESS_TOKEN_GENERATION_ALGORITHM,
};
